#!/usr/bin/env bash
# # # # # # # # # # # # # # # # # # # # # # # # #
# To setup all the hooks execute:               #
# git config --local core.hooksPath .githooks/  #
# # # # # # # # # # # # # # # # # # # # # # # # #

echo "Running detekt check..."
OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT
