name: pull-request-workflow
run-name: Checking pull request submitted by ${{ github.actor }}
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [ opened, reopened, synchronize ]
jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle
      - name: run detekt
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: detekt
      - name: build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          # exclude sample app because google-services.json is put under .gitignore
          arguments: "assemble -x sample-android:assemble"
      - name: run tests
        uses: gradle/gradle-build-action@v2.4.2
        with:
          # exclude all samples because there is no any tests there
          arguments: "test -x sample-android:test -x sample-common:test -x sample-jvm:test"
